/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 01 15:44:55 GMT 2023
 */

package calcolatrice;

import org.junit.Test;
import static org.junit.Assert.*;
import calcolatrice.calcolatrice;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class calcolatrice_ESTest extends calcolatrice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      int int0 = calcolatrice0.somma(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      int int0 = calcolatrice0.somma(1, 4147);
      assertEquals(4148, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      int int0 = calcolatrice0.somma(890, (-4069));
      assertEquals((-3179), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      double double0 = calcolatrice0.divisione(0, 4147);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      double double0 = calcolatrice0.divisione((-53), (-1297));
      assertEquals(0.040863531225905934, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      calcolatrice calcolatrice0 = new calcolatrice();
      double double0 = calcolatrice0.divisione((-1), 0);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }
}
